// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/huabuyu/Documents/perfect-design/node_modules/.pnpm/registry.npmmirror.com+dumi@2.1.9_@babel+core@7.21.0_@types+node@18.19.64_@types+react@18.0.2_lyyvmadyhp6etqdg5q4guqeu5i/node_modules/dumi/theme-default/slots/RtlSwitch/index.js';
